modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="create_bs"
version="1.1.0-1.21.1"
displayName="Create Better Storages"
authors="LopyLuna"
description='''
Adds tiered item vaults to Create.
'''

[[dependencies.create_bs]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.create_bs]]
modId="neoforge"
type="required"
versionRange="[21.1.125,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_bs]]
modId="create"
type="required"
versionRange="[6.0,7.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_bs]]
modId="flywheel"
type="required"
versionRange="[1.0,2.0)"
ordering="AFTER"
side="CLIENT"

[[dependencies.create_bs]]
modId="ponder"
type="required"
versionRange="[1.0,2.0)"
ordering="AFTER"
side="CLIENT"

[[dependencies.create_bs]]
modId="curios"
type="optional"
versionRange="[9.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_bs]]
modId="jei"
type="optional"
versionRange="[19.0,)"
ordering="AFTER"
side="CLIENT"